# -*- coding: utf-8 -*-
"""Sistema Bancário

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166jQTvpA9JPs1dYwdFKYBOC35P7YF3NK
"""

class SistemaBancario:
    def __init__(self):
        self.saldo = 0.0
        self.extrato = []
        self.saques_diarios = 0
        self.limite_saque = 500.0
        self.max_saques_diarios = 3

    def depositar(self, valor):
        if valor > 0:
            self.saldo += valor
            self.extrato.append(f"Depósito: R$ {valor:.2f}")
            print(f"Depósito de R$ {valor:.2f} realizado com sucesso!")
        else:
            print("O valor do depósito deve ser positivo.")

    def sacar(self, valor):
        if self.saques_diarios >= self.max_saques_diarios:
            print("Limite de saques diários atingido.")
        elif valor > self.limite_saque:
            print(f"O valor máximo para saque é de R$ {self.limite_saque:.2f}.")
        elif valor > self.saldo:
            print("Saldo insuficiente.")
        elif valor > 0:
            self.saldo -= valor
            self.extrato.append(f"Saque: R$ {valor:.2f}")
            self.saques_diarios += 1
            print(f"Saque de R$ {valor:.2f} realizado com sucesso!")
        else:
            print("O valor do saque deve ser positivo.")

    def exibir_extrato(self):
        print("\nExtrato:")
        if not self.extrato:
            print("Não foram realizadas movimentações.")
        else:
            for transacao in self.extrato:
                print(transacao)
            print(f"Saldo atual: R$ {self.saldo:.2f}")
        print()

#Sistema bancário
sistema_bancario = SistemaBancario()

sistema_bancario.depositar(1000.0)
sistema_bancario.sacar(300.0)
sistema_bancario.sacar(200.0)
sistema_bancario.sacar(50.0)  # Deve exibir mensagem de limite de saques diários atingido
sistema_bancario.exibir_extrato()